# Fuente 3 - Radar Doppler

## Objetivo

Definir la fuente primaria tipo sensor que será utilizada para representar la medición de velocidad de los vehículos en el tramo de estudio.

Para esta etapa se toma como referencia un radar Doppler comercial real y se revisan sus características técnicas a partir de documentación del fabricante.

## 1. Sensor de referencia

Para representar la fuente primaria del proyecto se seleccionó como referencia el radar Doppler **OmniPreSense OPS243-A**.

El fabricante presenta este dispositivo como un sensor de radar de corto alcance aplicable al monitoreo de tráfico. El sensor permite detectar movimiento y reportar la velocidad y dirección de los objetos ubicados dentro de su campo de detección. (https://omnipresense.com/product/ops243-doppler-radar-sensor/)

Su selección para el proyecto se debe principalmente a que permite medir directamente la variable que se necesita estudiar: la velocidad de circulación de los vehículos. Además, es un sistema no intrusivo, ya que la medición puede realizarse desde el costado de la vía sin necesidad de intervenir el pavimento.

### Fuentes técnicas consultadas

- OmniPreSense. OPS243-A Doppler Radar Sensor.

  (https://omnipresense.com/product/ops243-doppler-radar-sensor/)
- OmniPreSense. OPS243 Radar Sensor Product Brief.

  (https://omnipresense.com/wp-content/uploads/2024/01/OPS243-Product-Brief_004-F.pdf)

- OmniPreSense. OPS24x API Interface.
  
  (https://omnipresense.com/wp-content/uploads/2026/09/AN-010-AF_API_Interface.pdf)

## 2. Características técnicas relevantes

Las siguientes características se toman de la documentación oficial de OmniPreSense y se utilizarán como referencia para definir posteriormente la simulación de la fuente primaria del proyecto.

| Característica | Valor de referencia |
|---|---|
| Fabricante | OmniPreSense |
| Modelo | OPS243-A |
| Tecnología | Radar Doppler |
| Aplicación indicada | Monitoreo de tráfico |
| Variable principal | Velocidad |
| Información adicional | Dirección de movimiento (Inbound/Outbound) |
| Frecuencia de operación | 24.00 - 24.25 GHz |
| Rango de detección publicado | 1 - 100 m |
| Precisión de velocidad | ±0.5 % |
| Ancho del haz | 20° azimut × 24° elevación (-3 dB) |
| Interfaces de la variante OPS243-A-CW-RP | USB / UART |
| Frecuencia de muestreo Doppler | Configurable; valor predeterminado de 10,000 muestras/s |
| Salida de información | Datos digitales procesados mediante API |

### Procedencia y utilidad de las características

Las especificaciones anteriores no corresponden a valores definidos arbitrariamente para la simulación. Se obtuvieron de la documentación oficial del fabricante y permiten establecer una referencia técnica para representar posteriormente el funcionamiento del sensor.

**Fabricante y modelo — OmniPreSense OPS243-A**

El modelo se identifica en el *OPS243 Radar Sensor Product Brief*, específicamente en la tabla de funcionalidades de la página 1 y en la sección **Ordering Information** de la página 2. Allí el OPS243-A aparece identificado como un sensor de tipo **Doppler**.

Este dato permite establecer exactamente qué dispositivo se está utilizando como referencia para la fuente primaria y evitar trabajar con un "radar Doppler" genérico sin especificaciones conocidas.

---

**Tecnología — Radar Doppler**

En la página 2 del *Product Brief*, sección **Ordering Information**, el OPS243-A aparece clasificado como **Doppler**. La misma clasificación aparece en la página 1 de *AN-010-AF API Interface Specification*, en la **Table 1. Radar Sensor Feature Matrix**.

Esta característica es importante porque el principio Doppler es el que permite obtener información sobre el movimiento y la velocidad del objeto detectado. Este principio será desarrollado con mayor detalle posteriormente en la actividad de adquisición de datos (DAQ).

---

**Aplicación — Monitoreo de tráfico**

En la página 1 del *OPS243 Radar Sensor Product Brief*, dentro de la sección **Functionality**, se incluye explícitamente **Traffic Monitoring**. La página oficial del producto también presenta el OPS243-A como un sensor apropiado para soluciones de monitoreo de tráfico.

Esta aplicación coincide directamente con el problema del proyecto, ya que se busca representar la medición de velocidad de vehículos que circulan por un tramo vial.

---

**Velocidad y dirección de movimiento**

En la página 1 del *Product Brief*, la tabla de funcionalidades indica que el OPS243-A permite detectar **movimiento, dirección y velocidad**. La página oficial del producto especifica además el reporte de dirección como **Inbound/Outbound**. La **Table 1** de la documentación AN-010-AF también confirma que el OPS243-A Doppler reporta movimiento, velocidad y dirección.

La velocidad será la variable principal de la fuente sensor. La dirección puede utilizarse como información complementaria para diferenciar el sentido en el que circula el vehículo.

---

**Frecuencia de operación — 24.00 a 24.25 GHz**

Se encuentra en la página 2 del *OPS243 Radar Sensor Product Brief*, sección **Electrical Specifications**, en el parámetro **Operating Frequency**.

Esta característica describe la banda de radiofrecuencia en la que trabaja físicamente el radar. No corresponde a la frecuencia con la que se almacenarán los registros de velocidad; son conceptos diferentes.

---

**Rango de detección — 1 a 100 m**

La página 1 del *Product Brief*, sección **Features**, indica un rango de detección de **1-100 m (3-328 ft)**. La página oficial del OPS243-A publica el mismo rango.

La documentación AN-010-AF presenta además un rango de **50-100 m para el OPS243-A bajo la condición RCS = 10**, por lo que el alcance real depende de las características del objeto detectado y de las condiciones de operación.

Para el proyecto se utilizará el valor 1-100 m únicamente como rango publicado por el fabricante y no como garantía de que cualquier vehículo será detectado a 100 m.

## 3. Variables de la fuente para el proyecto

A partir de la información que puede proporcionar el radar y del contexto necesario para almacenar cada medición, se plantea inicialmente la siguiente estructura de datos.

| Variable | Procedencia | Descripción |
|---|---|---|
| `velocidad_kmh` | Medición del radar | Velocidad detectada del vehículo en km/h |
| `direccion_movimiento` | Medición del radar | Sentido del movimiento detectado por el sensor |
| `timestamp` | Sistema de adquisición | Fecha y hora en que se registra la medición |
| `id_sensor` | Sistema de adquisición | Identificador del radar que produjo la medición |
| `latitud_sensor` | Configuración del sistema | Ubicación fija donde se instala conceptualmente el sensor |
| `longitud_sensor` | Configuración del sistema | Ubicación fija donde se instala conceptualmente el sensor |

## 4. Contribución de la fuente al problema

La fuente de radar aporta información sobre el comportamiento de velocidad de los vehículos que circulan por el tramo estudiado.

La geometría vial permite conocer la forma y características espaciales de la carretera, mientras que los registros históricos de siniestralidad muestran qué eventos han ocurrido en el sector. Sin embargo, ninguna de estas dos fuentes permite conocer directamente a qué velocidades están circulando los vehículos.

El radar complementa las otras fuentes al proporcionar mediciones de velocidad en el mismo contexto espacial. De esta forma, las tres fuentes permiten estudiar conjuntamente:

- cómo es geométricamente el tramo vial;
- cómo circulan los vehículos por el tramo;
- qué antecedentes de siniestralidad existen en el mismo sector.

La integración posterior de estas fuentes permitirá caracterizar las condiciones del tramo, sin afirmar que las velocidades medidas por el radar correspondan directamente a las velocidades de los vehículos involucrados en los siniestros históricos.

## 5. Simulación de la adquisición de datos

Como no contamos físicamente con el radar **OmniPreSense OPS243-A**, se simularán los datos que este sensor podría generar al detectar vehículos.

Para la simulación se tendrán en cuenta:

- velocidad máxima del proyecto: **200 km/h**
- frecuencia de muestreo: **20.000 muestras/s**
- resolución de velocidad: **0,4356 km/h**
- dirección: **INBOUND** o **OUTBOUND**
- sensor: **RD-OPS243-01**
- latitud del sensor: **6.220055**
- longitud del sensor: **-75.562449**

La ubicación corresponde al punto fijo definido para el radar en la curva de **La Asomadera #2**, sobre la Avenida Las Palmas.

De acuerdo con la orientación planteada para el sensor:

- **INBOUND** se asociará con **Av. Las Palmas >Occidente**.
- **OUTBOUND** se asociará con **Av. Las Palmas >Oriente**.

Las **20.000 muestras por segundo** corresponden al funcionamiento interno del radar para calcular la velocidad, no a la cantidad de vehículos registrados.

Se simularán **1.000 detecciones de vehículos durante un día**. Los horarios, las velocidades y la cantidad de vehículos son generados únicamente para la simulación y no representan mediciones reales realizadas en la Avenida Las Palmas.

In [ ]:
import numpy as np
import pandas as pd

# Semilla para que la simulación sea reproducible
rng = np.random.default_rng(42)

# ---------------------------------------------------------
# Parámetros definidos para la simulación
# ---------------------------------------------------------

cantidad_registros = 1000
fecha_simulacion = pd.Timestamp("2026-03-14")

# Identificación y ubicación fija del sensor
id_sensor = "RD-OPS243-01"
latitud_sensor = 6.220055
longitud_sensor = -75.562449

# Características utilizadas como referencia
resolucion_kmh = 0.4356
velocidad_maxima_proyecto = 200

# ---------------------------------------------------------
# Simulación de la hora de paso de los vehículos
# ---------------------------------------------------------

# Se seleccionan segundos diferentes dentro de un día
segundos_dia = rng.choice(
    24 * 60 * 60,
    size=cantidad_registros,
    replace=False
)

segundos_dia.sort()

timestamps = (
    fecha_simulacion
    + pd.to_timedelta(segundos_dia, unit="s")
)

# ---------------------------------------------------------
# Simulación de velocidad
# ---------------------------------------------------------

# Rango utilizado únicamente para generar datos de ejemplo
velocidades_simuladas = rng.uniform(
    20,
    120,
    size=cantidad_registros
)

# Se ajustan los valores a la resolución utilizada como referencia
velocidades_cuantificadas = (
    np.round(velocidades_simuladas / resolucion_kmh)
    * resolucion_kmh
)

velocidades_cuantificadas = np.round(
    velocidades_cuantificadas,
    4
)

# ---------------------------------------------------------
# Simulación de dirección
# ---------------------------------------------------------

# Para la orientación definida:
# INBOUND  -> Av. Las Palmas >Occidente
# OUTBOUND -> Av. Las Palmas >Oriente

direcciones = rng.choice(
    ["INBOUND", "OUTBOUND"],
    size=cantidad_registros
)

# ---------------------------------------------------------
# Construcción del conjunto de datos
# ---------------------------------------------------------

df_radar_simulado = pd.DataFrame({
    "timestamp": timestamps,
    "velocidad_kmh": velocidades_cuantificadas,
    "direccion_movimiento": direcciones,
    "id_sensor": id_sensor,
    "latitud_sensor": latitud_sensor,
    "longitud_sensor": longitud_sensor
})

df_radar_simulado.head(10)

,timestamp,velocidad_kmh,direccion_movimiento,id_sensor,latitud_sensor,longitud_sensor
0,2026-03-14 00:06:17,26.1360,INBOUND,RD-OPS243-01,6.220055,-75.562449
1,2026-03-14 00:07:01,65.7756,INBOUND,RD-OPS243-01,6.220055,-75.562449
2,2026-03-14 00:07:35,33.1056,OUTBOUND,RD-OPS243-01,6.220055,-75.562449
3,2026-03-14 00:07:48,35.2836,INBOUND,RD-OPS243-01,6.220055,-75.562449
4,2026-03-14 00:07:52,83.1996,INBOUND,RD-OPS243-01,6.220055,-75.562449
5,2026-03-14 00:09:19,59.2416,OUTBOUND,RD-OPS243-01,6.220055,-75.562449
6,2026-03-14 00:10:08,112.3848,OUTBOUND,RD-OPS243-01,6.220055,-75.562449
7,2026-03-14 00:10:29,51.8364,INBOUND,RD-OPS243-01,6.220055,-75.562449
8,2026-03-14 00:11:16,92.7828,OUTBOUND,RD-OPS243-01,6.220055,-75.562449
9,2026-03-14 00:14:09,66.2112,INBOUND,RD-OPS243-01,6.220055,-75.562449

### Verificación de los registros simulados

Se realiza una verificación básica del conjunto generado para comprobar la cantidad de registros, el rango de velocidades, las direcciones presentes, los tipos de datos y la ubicación asignada al sensor.

In [ ]:
print("Registros simulados:", len(df_radar_simulado))

print(
    "Velocidad mínima:",
    df_radar_simulado["velocidad_kmh"].min(),
    "km/h"
)

print(
    "Velocidad máxima:",
    df_radar_simulado["velocidad_kmh"].max(),
    "km/h"
)

print("\nRegistros por dirección:")
print(
    df_radar_simulado[
        "direccion_movimiento"
    ].value_counts()
)

print("\nUbicación del sensor:")
print(
    df_radar_simulado[
        ["id_sensor", "latitud_sensor", "longitud_sensor"]
    ].drop_duplicates()
)

print("\nTipos de datos:")
print(df_radar_simulado.dtypes)

Registros simulados: 1000
Velocidad mínima: 20.0376 km/h
Velocidad máxima: 119.79 km/h

Registros por dirección:
direccion_movimiento
INBOUND     524
OUTBOUND    476
Name: count, dtype: int64

Ubicación del sensor:
      id_sensor  latitud_sensor  longitud_sensor
0  RD-OPS243-01        6.220055       -75.562449

Tipos de datos:
timestamp               datetime64[ns]
velocidad_kmh                  float64
direccion_movimiento            object
id_sensor                       object
latitud_sensor                 float64
longitud_sensor                float64
dtype: object

### Almacenamiento de la fuente adquirida

Los registros simulados del radar se almacenan en un archivo CSV que representa la información digital que recibiría el sistema de adquisición.

Cada registro contiene la fecha y hora de la detección, la velocidad del vehículo, la dirección de movimiento identificada como `INBOUND` o `OUTBOUND`, el identificador del sensor y sus coordenadas fijas de ubicación.

La ubicación del sensor permitirá posteriormente relacionar espacialmente las mediciones del radar con la geometría de la Avenida Las Palmas obtenida mediante la fuente Segmento Vial.

El archivo corresponde a una fuente simulada y no representa mediciones reales realizadas sobre la Avenida Las Palmas.

In [ ]:
nombre_archivo = "radar_velocidad_simulada.csv"

df_radar_simulado.to_csv(
    nombre_archivo,
    index=False,
    sep=";",
    encoding="utf-8-sig"
)

print("Archivo generado:", nombre_archivo)
print("Registros almacenados:", len(df_radar_simulado))

Archivo generado: radar_velocidad_simulada.csv
Registros almacenados: 1000

###DESCARGAR

In [ ]:
from google.colab import files

files.download("radar_velocidad_simulada.csv")

## 6. Calidad de los datos

Se revisan las variables generadas por la simulación del radar, verificando datos faltantes y consistencia con las condiciones definidas para el proyecto.

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display

# =========================================================
# 6. CALIDAD DE LOS DATOS - RADAR DOPPLER
# =========================================================

# Leemos directamente el archivo generado
df = pd.read_csv(
    "radar_velocidad_simulada.csv",
    sep=";"
)

print("Registros analizados:", len(df))
print("Variables analizadas:", len(df.columns))


# ---------------------------------------------------------
# 1. Datos faltantes
# ---------------------------------------------------------

marcadores_sin_informacion = {
    "ND",
    "N/D",
    "SIN INFORMACION",
    "SIN INFORMACIÓN",
    "NO DISPONIBLE",
    "NULL"
}


def analizar_ausencia(serie):

    faltante = serie.isna().copy()

    codificado = pd.Series(
        False,
        index=serie.index
    )

    if (
        pd.api.types.is_object_dtype(serie)
        or pd.api.types.is_string_dtype(serie)
    ):

        texto = (
            serie.astype("string")
            .str.strip()
        )

        faltante = (
            faltante
            | texto.eq("").fillna(False)
        )

        codificado = (
            texto.str.upper()
            .isin(marcadores_sin_informacion)
            .fillna(False)
        )

    return faltante, codificado


faltantes = {}
faltantes_codificados = {}

for columna in df.columns:

    mascara_faltante, mascara_codificada = (
        analizar_ausencia(df[columna])
    )

    faltantes[columna] = mascara_faltante
    faltantes_codificados[columna] = mascara_codificada


# ---------------------------------------------------------
# 2. Errores
# ---------------------------------------------------------

errores = {
    columna: pd.Series(
        False,
        index=df.index
    )
    for columna in df.columns
}

criterios = {
    columna: "Se revisan datos faltantes"
    for columna in df.columns
}


# timestamp
timestamp = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)

errores["timestamp"] = (
    ~faltantes["timestamp"]
    & timestamp.isna()
)

criterios["timestamp"] = (
    "Fecha y hora válidas"
)


# velocidad
velocidad = pd.to_numeric(
    df["velocidad_kmh"],
    errors="coerce"
)

errores["velocidad_kmh"] = (
    ~faltantes["velocidad_kmh"]
    & (
        velocidad.isna()
        | ~velocidad.between(0, 200)
    )
)

criterios["velocidad_kmh"] = (
    "Numérica entre 0 y 200 km/h"
)


# dirección
errores["direccion_movimiento"] = (
    ~faltantes["direccion_movimiento"]
    & ~df["direccion_movimiento"]
    .isin(["INBOUND", "OUTBOUND"])
)

criterios["direccion_movimiento"] = (
    "Solo INBOUND u OUTBOUND"
)


# id_sensor
errores["id_sensor"] = (
    ~faltantes["id_sensor"]
    & (
        df["id_sensor"]
        != "RD-OPS243-01"
    )
)

criterios["id_sensor"] = (
    "Debe ser RD-OPS243-01"
)


# latitud
latitud = pd.to_numeric(
    df["latitud_sensor"],
    errors="coerce"
)

errores["latitud_sensor"] = (
    ~faltantes["latitud_sensor"]
    & (
        latitud.isna()
        | ~np.isclose(
            latitud,
            6.220055,
            rtol=0,
            atol=1e-6
        )
    )
)

criterios["latitud_sensor"] = (
    "Debe corresponder a 6.220055"
)


# longitud
longitud = pd.to_numeric(
    df["longitud_sensor"],
    errors="coerce"
)

errores["longitud_sensor"] = (
    ~faltantes["longitud_sensor"]
    & (
        longitud.isna()
        | ~np.isclose(
            longitud,
            -75.562449,
            rtol=0,
            atol=1e-6
        )
    )
)

criterios["longitud_sensor"] = (
    "Debe corresponder a -75.562449"
)


# =========================================================
# 3. TABLA 1 - TODAS LAS VARIABLES
# =========================================================

tabla_calidad_completa = pd.DataFrame({
    "Variable": df.columns,
    "Tipo de dato": df.dtypes.astype(str).values,
    "Datos faltantes": [
        int(faltantes[col].sum())
        for col in df.columns
    ],
    "Faltantes codificados": [
        int(faltantes_codificados[col].sum())
        for col in df.columns
    ],
    "Datos con error": [
        int(errores[col].sum())
        for col in df.columns
    ],
    "Criterio revisado": [
        criterios[col]
        for col in df.columns
    ]
})


print("\nTABLA 1 - CALIDAD DE TODAS LAS VARIABLES")
display(tabla_calidad_completa)


# =========================================================
# 4. TABLA 2 - VARIABLES RELEVANTES
# =========================================================

# En el radar todas las variables generadas
# son relevantes para el proyecto.

variables_relevantes = [
    "timestamp",
    "velocidad_kmh",
    "direccion_movimiento",
    "id_sensor",
    "latitud_sensor",
    "longitud_sensor"
]


tabla_calidad_relevantes = (
    tabla_calidad_completa[
        tabla_calidad_completa["Variable"]
        .isin(variables_relevantes)
    ]
    .reset_index(drop=True)
)


print("\nTABLA 2 - VARIABLES RELEVANTES PARA EL PROYECTO")
display(tabla_calidad_relevantes)


# =========================================================
# 5. RESUMEN
# =========================================================

ausencias = pd.DataFrame({
    col: (
        faltantes[col]
        | faltantes_codificados[col]
    )
    for col in variables_relevantes
})

errores_df = pd.DataFrame({
    col: errores[col]
    for col in variables_relevantes
})


print("\nRESUMEN")

print(
    "Registros con alguna ausencia:",
    int(ausencias.any(axis=1).sum())
)

print(
    "Registros con algún error:",
    int(errores_df.any(axis=1).sum())
)

Registros analizados: 1000
Variables analizadas: 6

TABLA 1 - CALIDAD DE TODAS LAS VARIABLES

,Variable,Tipo de dato,Datos faltantes,Faltantes codificados,Datos con error,Criterio revisado
0,timestamp,object,0,0,0,Fecha y hora válidas
1,velocidad_kmh,float64,0,0,0,Numérica entre 0 y 200 km/h
2,direccion_movimiento,object,0,0,0,Solo INBOUND u OUTBOUND
3,id_sensor,object,0,0,0,Debe ser RD-OPS243-01
4,latitud_sensor,float64,0,0,0,Debe corresponder a 6.220055
5,longitud_sensor,float64,0,0,0,Debe corresponder a -75.562449

TABLA 2 - VARIABLES RELEVANTES PARA EL PROYECTO

,Variable,Tipo de dato,Datos faltantes,Faltantes codificados,Datos con error,Criterio revisado
0,timestamp,object,0,0,0,Fecha y hora válidas
1,velocidad_kmh,float64,0,0,0,Numérica entre 0 y 200 km/h
2,direccion_movimiento,object,0,0,0,Solo INBOUND u OUTBOUND
3,id_sensor,object,0,0,0,Debe ser RD-OPS243-01
4,latitud_sensor,float64,0,0,0,Debe corresponder a 6.220055
5,longitud_sensor,float64,0,0,0,Debe corresponder a -75.562449

RESUMEN
Registros con alguna ausencia: 0
Registros con algún error: 0